function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 21-Mar-2021 11:06:13

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Marker','o','Parent',axes1);
set(plot1(1),'DisplayName','pbs 0 min');
set(plot1(2),'DisplayName','pbs 1 min');
set(plot1(3),'DisplayName','pbs 10 min');
set(plot1(4),'DisplayName','pbs 100 min');

% Create ylabel
ylabel('Plasmolysis Events/Micron Post-Hyperosmotic Shock');

% Create xlabel
xlabel('Time (minutes after hypershock');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[-1 11]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0 0.5]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'XTick',[0 10]);
% Create legend
legend(axes1,'show');

