%growthRate_overColony.m
%
%Zarina Akbary
%01/25/2020
%
%Average and plot growth rate data generated by multiple FluoColonyTrack.m runs to one
%figure and plot growth rate over colony
%Save figure to the main folder

clear, close all

%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%dSigM reanalysis downshift
folder=['C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01072020_dSigM_reanalysis'];

%Add path and load FCT data from each figure of interest
addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01072020_dSigM_reanalysis\01072020_Series1_P1'));
fig1= load(['01072020_Series1_P1_FCT.mat'], 'tmid', 'eAsmooth', 'Ncells')

addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01072020_dSigM_reanalysis\01072020_Series2_P1'));
fig2=load(['01072020_Series2_P1_FCT.mat'], 'tmid', 'eAsmooth', 'Ncells')

addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01072020_dSigM_reanalysis\01072020_Series2_P2'));
fig3=load(['01072020_Series2_P2_FCT.mat'], 'tmid', 'eAsmooth', 'Ncells')

addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01072020_dSigM_reanalysis\01072020_Series3_P1'));
fig4=load(['01072020_Series3_P1_FCT.mat'], 'tmid', 'eAsmooth', 'Ncells')

vector1 = fig1.Ncells/(fig1.Ncells(1)); 
vector2 = fig2.Ncells/(fig2.Ncells(1));
vector3 = fig3.Ncells/(fig3.Ncells(1));
vector4 = fig4.Ncells/(fig4.Ncells(1));

%Generate figure
figure
hold on
plot(vector1(2:end),fig1.eAsmooth*3600)
plot(vector2(2:end),fig2.eAsmooth*3600)
plot(vector3(2:end),fig3.eAsmooth*3600)
plot(vector4(2:end),fig4.eAsmooth*3600)
xlabel('Colony Size (# of cells)')
ylabel('Growth Rate (s^{-1})')
fig2pretty
%cd(folder)
%savefig(['01072020_dSigM_reanalysis_growthOverColony.fig'])

%%%%Average growth rate
smoothAvg = zeros(1,121);

for i=1:121
    aSmooth=[fig1.eAsmooth(i)*3600,fig2.eAsmooth(i)*3600,fig3.eAsmooth(i)*3600,fig4.eAsmooth(i)*3600];
    smoothAvg(i)=sum(aSmooth)/4;
end

%Generate figure
figure
plot(fig4.tmid/3600, smoothAvg)
xlabel('Time (h)')
ylabel('Growth Rate (s^{-1})')
fig2pretty

%Plot data
figure
plot(time,Ncells/(Ncells(1)))
xlabel('Time (h)')
ylabel(strcat('Colony Size (# of cells) threshold = ', num2str(thresh)))
fig2pretty

%%%%%%%%yhdL reanalysis
% folder=['C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01092020_yhdL_reanalysis'];
% 
% %Add path and load FCT data from each figure of interest
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01092020_yhdL\01092020_Series1_P1'));
% fig1= load(['01092020_Series1_P1_FCT_final.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01092020_yhdL_reanalysis\01092020_Series2_P1'));
% fig2=load(['01092020_Series2_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01092020_yhdL_reanalysis\01092020_Series3_P1'));
% fig3=load(['01092020_Series3_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01092020_yhdL_reanalysis\01092020_Series3_P2'));
% fig4=load(['01092020_Series3_P2_FCT.mat'], 'tmid', 'eAsmooth')
% 
% %Generate figure
% figure
% hold on
% plot(fig1.tmid/3600,fig1.eAsmooth*3600)
% plot(fig2.tmid/3600,fig2.eAsmooth*3600)
% plot(fig3.tmid/3600,fig3.eAsmooth*3600)
% plot(fig4.tmid/3600,fig4.eAsmooth*3600)
% xlabel('Time (h)')
% ylabel('Growth Rate (s^{-1})')
% fig2pretty
% cd(folder)
% savefig(['01092020_yhdL_reanalysis_growthRate.fig'])

%%%%%%%%WT sgRNA
% folder=['C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01142020_WTsgRNA'];
% 
% %Add path and load FCT data from each figure of interest
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01142020_WTsgRNA\01142020_Series1_P1'));
% fig1= load(['01142020_Series1_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01142020_WTsgRNA\01142020_Series2_P1'));
% fig2=load(['01142020_Series2_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01142020_WTsgRNA\01142020_Series3_P1'));
% fig3=load(['01142020_Series3_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01142020_WTsgRNA\01142020_Series4_P1'));
% fig4=load(['01142020_Series4_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% %Generate figure
% figure
% hold on
% plot(fig1.tmid/3600,fig1.eAsmooth*3600)
% plot(fig2.tmid/3600,fig2.eAsmooth*3600)
% plot(fig3.tmid/3600,fig3.eAsmooth*3600)
% plot(fig4.tmid/3600,fig4.eAsmooth*3600)
% xlabel('Time (h)')
% ylabel('Growth Rate (s^{-1})')
% fig2pretty
% cd(folder)
% savefig(['01142020_WTsgRNA_growthRate.fig'])

% %%%%%%%%WTdownshift
% folder=['C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01162020_WTdownshift'];
% 
% %Add path and load FCT data from each figure of interest
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01162020_WTdownshift\01162020_Series1_P1'));
% fig1= load(['01162020_Series1_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01162020_WTdownshift\01162020_Series2_P1'));
% fig2=load(['01162020_Series2_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01162020_WTdownshift\01162020_Series3_P1'));
% fig3=load(['01162020_Series3_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01162020_WTdownshift\01162020_Series4_P1'));
% fig4=load(['01162020_Series4_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% %Generate figure
% figure
% hold on
% plot(fig1.tmid/3600,fig1.eAsmooth*3600)
% plot(fig2.tmid/3600,fig2.eAsmooth*3600)
% plot(fig3.tmid/3600,fig3.eAsmooth*3600)
% plot(fig4.tmid/3600,fig4.eAsmooth*3600)
% xlabel('Time (h)')
% ylabel('Growth Rate (s^{-1})')
% fig2pretty
% cd(folder)
% savefig(['01162020_WTdownshift_growthRate.fig'])

% %%%%%%%%yhdL downshift
% folder=['C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01232020_yhdLdownshift'];
% colonylab = {'Colony 1 (S1P1)', 'Colony 2 (S1P2)', 'Colony 3 (S2P1)', 'Colony 4 (S4P1)'};
% 
% %Add path and load FCT data from each figure of interest
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01232020_yhdLdownshift\01232020_Series1_P1'));
% fig1= load(['01232020_Series1_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01232020_yhdLdownshift\01232020_Series1_P2'));
% fig2=load(['01232020_Series1_P2_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01232020_yhdLdownshift\01232020_Series2_P1'));
% fig3=load(['01232020_Series2_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% addpath(genpath('C:\Users\zarin\Downloads\NYU\R2_Rojas Lab\growthRate_01232020_yhdLdownshift\01232020_Series4_P1'));
% fig4=load(['01232020_Series4_P1_FCT.mat'], 'tmid', 'eAsmooth')
% 
% %Generate figure
% figure
% hold on
% plot(fig1.tmid/3600,fig1.eAsmooth*3600)
% plot(fig2.tmid/3600,fig2.eAsmooth*3600)
% plot(fig3.tmid/3600,fig3.eAsmooth*3600)
% plot(fig4.tmid/3600,fig4.eAsmooth*3600)
% xlabel('Time (h)')
% ylabel('Growth Rate (s^{-1})')
% legend(colonylab)
% fig2pretty
% cd(folder)
% savefig(['01232020_yhdLdownshift_growthRate.fig'])
